name: BotMate Publish

on:
  release:
    types:
      - created

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: |
          yarn install
      - name: Bootstraping Packages
        run: |
          npx lerna bootstrap
      - name: Building Packages
        run: yarn gulp
        env:
          CI: false

      - name: Publishing to NPM
        working-directory: ./packages/server
        run: |
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
